FROM node:20.11.1-alpine as builder

RUN npm install -g npm@latest

WORKDIR /app

COPY package*.json ./

RUN npm i

COPY . .


RUN npm run build

FROM node:20.11.1-alpine

WORKDIR /app

COPY --from=builder /app/dist .
COPY ./prisma ./prisma

RUN npm install -g npm@latest
RUN npm i @nestjs/core @nestjs/swagger uuid http-status-codes @nestjs/config @nestjs/platform-express prisma @prisma/client tsx

ARG PORT=5000
ENV PORT ${PORT}
EXPOSE ${PORT}

RUN npx prisma generate

CMD ["npx","tsx","watch", "main"]
