version: '3.9'
services:
  db:
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
#      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
    ports:
      - "${PORT_DB}:${PORT_DB}"
    networks:
      - bridge-network
    env_file:
      - .env


  nextjs:
    restart: always
    container_name: nextJs
    image: mdz1985/nodejs2024q1-service-nextjs
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/app/src
      - ./prisma/schema.prisma:/app/prisma/schema.prisma
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - bridge-network
    env_file:
      - .env


volumes:
  postgres-data:
    driver: local
  postgres-logs:
    driver: local
  node_modules:
    driver: local
  src_volume:
    driver: local



networks:
  bridge-network:
    driver: bridge
