version: '3.8'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - bridge-network
    restart: on-failure

  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
    ports:
      - "5432:5432"
    networks:
      - bridge-network
    restart: on-failure


volumes:
  postgres-data:
    driver: local
  postgres-logs:
    driver: local


networks:
  bridge-network:
    driver: bridge
