version: '3.9'
services:
  db:
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      DATABASE_URL: postgresql://myuser:mypassword@mydatabase:5432/mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
    ports:
      - "5432:5432"
    networks:
      - bridge-network
    env_file:
      - .env


  nextjs:
    restart: always
    container_name: nextJs
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - bridge-network
    env_file:
      - .env


volumes:
  postgres-data:
    driver: local
  postgres-logs:
    driver: local
  node_modules_volume:
    driver: local
  src_volume:
    driver: local



networks:
  bridge-network:
    driver: bridge
